### ISSUE TITLE
Remove all signs of Address Book

### ISSUE THREAD

**Issue by kev-inc** [CS2103-AY1819S2-W17-4/main#101]
Hi everyone how shall we do this

**Comment by rahulb99** [comment]
`@Ignore` all the tests and delete class files or refactor for Epiggy?

**Comment by tehwenyi** [comment]
Need to standardise that AddressBook will be refactored to EPiggy and not ePiggy or Epiggy.

**Comment by tehwenyi** [comment]
Done in #142

**Comment by rahulb99** [comment]
I will be removing everything related to the old code.
