### ISSUE TITLE
Tasks to complete for v1.3 

### ISSUE THREAD

**Issue by rahulb99** [CS2103-AY1819S2-W17-4/main#113]
Mock submissions for this week...
- [x] Everyone has updated UG

- [x] Everyone has updated DG

    - [x] features coming in v2.0 (share feature, I (@rahulb99 ) will write about that.)

- [x] Everyone has made their PPP

- [x] Everyone - try to complete your features by Monday. Tuesday we keep it as buffer. (Tuesday night is deadline)

**Comment by tehwenyi** [comment]
I think PPP is due the next milestone, because our lesson on guide to PPP is next week.

- [ ] Create *.jar file (@tehwenyi )

**Comment by rahulb99** [comment]
![image](https://user-images.githubusercontent.com/31964723/55273136-04f95580-5302-11e9-9f85-85cb7667f906.png)

**Comment by tehwenyi** [comment]
Okay! Will do.

- [ ] Remember to build jar file again before the release to take into account latest updates.

**Comment by yunjun199321** [comment]
Don't do the share feature.
