### ISSUE TITLE
CommandBox bug

### ISSUE THREAD

**Issue by rahulb99** [CS2103-AY1819S2-W17-4/main#145]
up and down arrow don't work. after entering the command, the command doesn't disappear from the box. someone fix this.

**Comment by yunjun199321** [comment]
I can't find this bug. What I did:
1. type an addExpense command, enter
2. type an addBudget command, enter
3. type an addBudget command again, enter
4. press up and down arrow and the command changes.
Can you write down the procedure of what to encouter the bug you found?
