### ISSUE TITLE
Cost parser - decimal places

### ISSUE THREAD

**Issue by tehwenyi** [CS2103-AY1819S2-W17-4/main#167]
It would be better if the parser for cost only allows a double of 2 decimal points to be taken in, rather than only show a double with 2 decimal points. 

This is because in real life, there shouldn't be any money which has more than 2 decimal places.

**Comment by kev-inc** [comment]
This has been fixed, the cost only accepts amounts up to 2 decimal points, and will throw an error if otherwise.
