### ISSUE TITLE
Increases test overall coverage

### ISSUE THREAD

**Issue by yunjun199321** [CS2103-AY1819S2-W17-4/main#234]
Everybody writes his test cases for own features.

- [x] overall coverage 50%

- [x] overall coverage 60%

- [x] overall coverage 70%

- [x] overall coverage 80%
-----------------------------------------------------
- [x] Try to reach 90%

**Comment by tehwenyi** [comment]
I've added the budget tests in ePiggyParserTest and tried adding for other commands but there were some issues so I commented out, please do the parser tests for your commands! @pdnm @kev-inc @yunjun199321 @rahulb99

**Comment by yunjun199321** [comment]
90%!!!!
