### ISSUE TITLE
Tag disappear

### ISSUE THREAD

**Issue by yunjun199321** [CS2103-AY1819S2-W17-4/main#247]
**Describe the bug**
Tags disappear after editing

**To Reproduce**
1. addExpense n/test $/100 t/one t/two
2. addAllowance n/test $/100 t/one t/two
3. editExpense 1 n/test $/100
4. editAllowance 2 n/test $/100

tags one and two disappear.

**Screenshots**
before edit 
![image](https://user-images.githubusercontent.com/25952837/55942750-a9bb5180-5c77-11e9-8f1e-282393d1d39f.png)

after edit
![image](https://user-images.githubusercontent.com/25952837/55942798-c48dc600-5c77-11e9-9684-b99247d3d466.png)

@kev-inc @pdnm

**Comment by kev-inc** [comment]
Fixed in #251
