### ISSUE TITLE
findExpense null pointer exception. addExpense, addAllowance show incorrect message

### ISSUE THREAD

**Issue by yunjun199321** [CS2103-AY1819S2-W17-4/main#248]
**Describe the bug**
1. findExpense n/food $/ t/ , enter. Causes null pointer exception error.

command don't handle the empty parameters. 
everyone pls check your commands and handle the empty parameters.

**Comment by tehwenyi** [comment]
What error message should it be?

**Comment by yunjun199321** [comment]
I think add commands are ok

**Comment by rahulb99** [comment]
but this is not a bug, i have mentioned in the UG that keywords cannot be empty. anyways, fixed in my latest PR...
