### ISSUE TITLE
sortExpense

### ISSUE THREAD

**Issue by yunjun199321** [CS2103-AY1819S2-W17-4/main#250]
sortExpense d/$/n/ and sortExpense d/ $/ n/ display different sort result.
![image](https://user-images.githubusercontent.com/25952837/55946049-8647d500-5c7e-11e9-8304-5f63b2069546.png)

![image](https://user-images.githubusercontent.com/25952837/55946028-7a5c1300-5c7e-11e9-800a-303e13273632.png)

**Comment by rahulb99** [comment]
solved... please pull from team repo
