### ISSUE TITLE
Add "Address" to the model

### ISSUE THREAD

**Issue by pdnm** [CS2103-AY1819S2-W17-4/main#31]
Problem: Expense Book needs to keep track of addresses

There are 2 choices:
* Address is a property of Item (each item is bound to a specific shop)
* Address is a property of Expense (the same item can be bought from multiple shops)

Tasks:
* Add Address to the model
* Update the command parser
* Show Address in the UI

**Comment by yunjun199321** [comment]
Address may not be an appropriate name. How about we call it the name of the shop.  The name of the shop can be one of the optional property of expense. We can put it under expense detail so that the user can check where he spends the money.
