### ISSUE TITLE
Basic methods for new model classes

### ISSUE THREAD

**Issue by pdnm** [CS2103-AY1819S2-W17-4/main#33]
The new model classes (`Expense`, `Item`, …) currently don't have `toString`, `equals` and other methods that the old model classes have.

Tasks:

* Implement these methods. Refer to the old model for what need to be added (`Person`, …)

**Comment by tehwenyi** [comment]
Added toString methods for Price, Period and Budget

**Comment by kev-inc** [comment]
Added toString methods for item, name and expense model. please review.
