### ISSUE TITLE
Need ePiggy icon

### ISSUE THREAD

**Issue by rahulb99** [CS2103-AY1819S2-W17-4/main#54]

**Comment by yunjun199321** [comment]
ePiggy does have an icon. Make sure your project is up-to-date.

**Comment by rahulb99** [comment]
I know it has an icon, i was asking where is it stored?

**Comment by yunjun199321** [comment]
main -> resources -> images -> address_book_32.png

**Comment by rahulb99** [comment]
ok, thanks! 👍
