### ISSUE TITLE
Why do we have different types of add commands?

### ISSUE THREAD

**Issue by rahulb99** [CS2103-AY1819S2-W17-4/main#56]
A single add command is just fine. `addCategory` command is not of any use. When user uses the simple `add` command, if he/she mentions the category in the input parameters, we will just append that category to list of categories. So `addCategory` is redundant. For same reason `addItem` command is also useless. 

Note that `addCategory` and `addItem` is mentioned **only** in the UG and have not been implemented.

**Comment by kev-inc** [comment]
yup i think that is a good point. i think we should just have 1 add command, and if the category or tag field is not in the list, we can just add it in.

**Comment by kev-inc** [comment]
@pdnm what do you think about this issue? should we have separate add commands for the expense, item and categories? or have 1 add command
