### ISSUE TITLE
Update Command summary

### ISSUE THREAD

**Issue by rahulb99** [CS2103-AY1819S2-W17-4/main#57]
@kev-inc Can you kindly update the command summary, i need it for my `help` command. 
`edit` command is old. (for new `edit` command, I am not sure how it'll work). Also if you can provide a single line description of all the commands.

**Comment by rahulb99** [comment]
how about this for `edit` command - 
`edit INDEX [n/EXPENSE_NAME] [$/COST] [c/CATEGORY] [d/DATE] [t/TAG…​]`
Eg: `edit 2 n/Lunch $/4 c/Food`

**Comment by kev-inc** [comment]
sure that sounds good, will complete the command summary

**Comment by kev-inc** [comment]
are you referring to the page that opens when the help command is entered? or the command summary in the userguide.adoc

**Comment by rahulb99** [comment]
Thanks!
