### ISSUE TITLE
Set Goal Command

### ISSUE THREAD

**Issue by kev-inc** [CS2103-AY1819S2-W17-4/main#61]
One aspect of a money saving app for kids is allowing them to save up for something they would like to buy. 

Adding setgoal command allows the child to set an amount they want to save up to (perhaps for a new toy etc) and the child can view his/her progress in hitting that amount.

I will be adding 2 new commands:

- [x] SetGoal command

- [x] ViewGoalProgress command

**Comment by yunjun199321** [comment]
Great. You can consider delete or modify goal too.
