### ISSUE TITLE
Add Allowance command?

### ISSUE THREAD

**Issue by kev-inc** [CS2103-AY1819S2-W17-4/main#71]
@CS2103-AY1819S2-W17-4/developers Do we need to have an add allowance command? Currently we have add expenses but without add allowance we will not be able to calculate to movement of the user's money, and I need a function like this to be able to calculate the net gain of the user's savings in order to reach their savings goal.

**Comment by tehwenyi** [comment]
I feel you can add a setAllowance command, like the setBudget command
