### ISSUE TITLE
Budget Bug to Fix

### ISSUE THREAD

**Issue by tehwenyi** [CS2103-AY1819S2-W17-4/main#81]
- [x] When a new budget is created, the endDate of the current budget is the startDate of the next budget. Hence, there is an overlap when the time of the expense added is on the end Date time 00:00:00 as it will be added to both budgets.
- [x] budgetList should be limited to a maximum capacity. Oldest budgets should be removed when new budgets are added when the list exceeds the maximum capacity.

- [x] Current budget should be shown on top, oldest budget at the bottom.

**Comment by kev-inc** [comment]
after i set a budget, when i do a addAllowance command, it will also be detected by the budget side. i do not think this behavior is correct. is is possible for the budgeting to ignore the allowance entries?

**Comment by yunjun199321** [comment]
Budget will be detected by a new expense. An allowance is the subclass of expense. Apply substitutability, Budget should also be detected by allowance. The behaviour seems correct but it is not what we want allowance to behave. Therefore, maybe our design wrong. 

I split the allowance and expense on the chart based on the name of the item. you can do it too.

**Comment by tehwenyi** [comment]
Fixed the problem where allowance is accounted for in budget.
