### ISSUE TITLE
Multiple uses of t/ in different commands

### ISSUE THREAD

**Issue by kev-inc** [CS2103-AY1819S2-W17-4/main#84]
The t/ tag is used to represent TAG in add commands, but is use to represent time period in days for the budgeting commands. Can we modify the prefix so that there will not be clashes?

**Comment by tehwenyi** [comment]
"t/" for TIME_PERIOD will be changed to "/p" instead.

**Comment by yunjun199321** [comment]
From now on, we can use tag/ and time_period/ instead of t/ because autocomplete is implemented.

**Comment by yunjun199321** [comment]
@tehwenyi You forgot to update user guide example after you change t/ to p/

**Comment by tehwenyi** [comment]
@yunjun199321 Fixed. Thanks for notifying!
